route:
    receiver: 'email-devs'
    group_by: ['environment', 'node']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 3h 
    routes:
        - match:
            envrionment: testing
          group_wait: 24h
          group_interval: 60m
          repeat_interval: 168h  
          receiver: 'email-devs'
        - match:
            envrionment: production
          receiver: 'email-devs'

receivers:
- name: 'email-devs'
  email_configs:
  - send_resolved: true
    html: "{{ .CommonAnnotations.description }}"
    text: "{{ .CommonAnnotations.description }}"
    #to: <emails>#
    #from: <from>#
    #smarthost: <host>#
    #auth_username: <user>#
    #auth_password: <password>#
