global:
  #smtp_smarthost: <host>#
  #smtp_from: <from>#
  #smtp_auth_username: <user>#
  #smtp_auth_password: <password>#

route:
    receiver: 'email'

receivers:
    - name: 'email'
      email_configs:
          - send_resolved: true
            to: <emails>
            html: "{{ .CommonAnnotations.description }}"
            text: "{{ .CommonAnnotations.description }}"

